services:
  app:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8081:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - LOKI_URL=http://loki:3100
      - TEMPO_URL=http://tempo:9411   
    volumes:
      - ./gateway/routes/docker.json:/app/routes/routes.json

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - 8082:3002

  users:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 8083:3001

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-local-config.yaml
    volumes:
      - ./conf/loki-config.yaml:/etc/loki/loki-local-config.yaml

  tempo:
    image: grafana/tempo:latest
    ports:
      - 14268:14268
      - 9411:9411

networks:
  default:
    name: app

volumes:
  grafana-data:
  prometheus-data:
