services:
  app:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8081:3000
    environment:
      - REDIS_URL=redis://redis:6379
      - LOKI_URL=http://loki:3100
      - TEMPO_URL=http://tempo:4318/v1/traces
    volumes:
      - ./gateway/routes/docker.json:/app/routes/routes.json

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - 8082:3002

  users:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - 8083:3001

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-local-config.yaml
    volumes:
      - ./conf/loki-config.yaml:/etc/loki/loki-local-config.yaml

  memcached:
    image: memcached:1.6.29
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4

  tempo:
    image: grafana/tempo:latest
    ports:
      - 14268:14268 # jaeger ingest
      - 3200:3200 # tempo
      - 9095:9095 # tempo grpc
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http
      - 9411:9411 # zipkin
    command: -config.file=/etc/tempo/local-config.yaml
    volumes:
      - ./conf/tempo-config.yaml:/etc/tempo/local-config.yaml

networks:
  default:
    name: app

volumes:
  grafana-data:
  prometheus-data:
